name: My second workflow

on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cowsay program
        run: sudo apt-get install -y cowsay

      - name: Execute the Cowsay
        run: cowsay -f dragon "Hello from dragon..!!" >> dragon.txt

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-txt-file
          path: dragon.txt

      - name: Sleep for 10 seconds
        run: sleep 10


  test_job:
    needs: build_job
    runs-on: ubuntu-latest

    steps:
      - name: Download dragon file
        uses: actions/download-artifact@v5
        with:
          name: dragon-txt-file

      - name: Test file exists
        run: grep -i "dragon" dragon.txt


  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest

    steps:
      - name: Download dragon file
        uses: actions/download-artifact@v5
        with:
          name: dragon-txt-file

      - name: Read dragon file
        run: cat dragon.txt

      - name: Deploy
        run: echo "Deploying application..."